gpt-4-1106-preview:
    - client_class: "openai.AzureOpenAI" 
      azure_deployment: "gpt-4" 
      api_version: "2024-05-01-preview" 
      api_key: "YOUR-API-KEY"
      azure_endpoint: "https://neils-m36cvicg-australiaeast.openai.azure.com/"